### ISSUE TITLE
Translation credits

### ISSUE THREAD

**Issue by hugok79** [pardus/pardus-update#5]
Hello,
If an application/software is translated into a language other than Turkish, it should display the name and email address of the translator so that users of that language can report spelling errors etc, to the translator, in my case, the Portuguese language.
Although the application is translated by me, only the name of the Turkish translator appears...
In various Xfce and Gnome applications, it is the translator's name that appears.
PS:This happens in all pardus applications

![Untitled](https://github.com/pardus/pardus-update/assets/16929048/eb67e14a-0f18-4fd4-b0a3-a926ddbfa4e6)

![mousepad](https://github.com/pardus/pardus-update/assets/16929048/fbc0e530-8618-4eaa-a4ef-7c0fc0b123dd)

**Comment by fthaltun** [comment]
Thanks for your feedback. You can translate the "translation-credits" string like "Name Surname <example@example.com>" now. We will update the structure to be this way in all our other applications.
